---
namespace: cisco
name: dnac
version: 6.7.6
readme: README.md
authors:
  - Rafael Campos <rcampos@altus.cr>
  - William Astorga <wastorga@altus.cr>
  - Jose Bogarin <jbogarin@altus.cr>
  - Bryan Vargas <bvargas@altus.cr>
  - Francisco Muñoz <fmunoz@altus.cr>
  - Madhan Sankaranarayanan (@madhansansel)
  - Rishita Chowdhary (@rishitachowdhary)
description: Ansible Modules for Cisco DNA Center
license_file: "LICENSE"
tags:
  - cisco
  - dnac
  - cloud
  - collection
  - networking
  - sdn
dependencies:
  ansible.utils: ">=2.0.0,<3.0"
repository: https://github.com/cisco-en-programmability/dnacenter-ansible
documentation: https://cisco-en-programmability.github.io/dnacenter-ansible/
homepage: https://github.com/cisco-en-programmability/dnacenter-ansible
issues: https://github.com/cisco-en-programmability/dnacenter-ansible/issues
