---
namespace: cisco
name: dnac
version: 6.27.0
readme: README.md
authors:
  - Rafael Campos <rcampos@altus.cr>
  - William Astorga <wastorga@altus.cr>
  - Jose Bogarin <jbogarin@altus.cr>
  - Bryan Vargas <bvargas@altus.cr>
  - Francisco Muñoz <fmunoz@altus.cr>
  - Madhan Sankaranarayanan <madsanka@cisco.com>
  - Pawan Singh <pawansi@cisco.com>
  - Rishita Chowdhary (@rishitachowdhary)
  - Muthu Rakesh Babu <mutbabu@cisco.com>
  - Akash Bhaskaran <akabhask@cisco.com>
  - Abinash Mishra <abimishr@cisco.com>
  - Abhishek Maheshwari <abmahesh@cisco.com>
  - Phan Nguyen <phannguy@cisco.com>
  - Rugvedi Kapse <rukapse@cisco.com>
  - Rangaprabhu Deenadayalu <radeenad@cisco.com>
  - Ajith Andrew J <jajandre@cisco.com>
  - Syed Khadeer Ahmed <syedkahm@cisco.com>
  - A Mohamed Rafeek <mabdulk2@cisco.com>
  - Trupti A Shetty <trashett@cisco.com>
  - Sonali Deepthi Kesali <skesali@cisco.com>
  - Megha Kandari <mekandar@cisco.com>

description: Ansible Modules for Cisco DNA Center
license_file: "LICENSE"
tags:
  - cisco
  - dnac
  - cloud
  - collection
  - networking
  - sdn
dependencies:
  ansible.utils: ">=2.0.0,<6.0"
repository: https://github.com/cisco-en-programmability/dnacenter-ansible
documentation: https://cisco-en-programmability.github.io/dnacenter-ansible/
homepage: https://github.com/cisco-en-programmability/dnacenter-ansible
issues: https://github.com/cisco-en-programmability/dnacenter-ansible/issues
