---
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Create
      cisco.dnac.sda_fabric_site:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        state: present
        fabricName: DNAC_Guide_Fabric
        siteNameHierarchy: Global/San Francisco

  # - name: Delete all
  #   cisco.dnac.sda_fabric_site:
  #     dnac_host: "{{ dnac_host }}"
  #     dnac_username: "{{ dnac_username }}"
  #     dnac_password: "{{ dnac_password }}"
  #     dnac_verify: "{{ dnac_verify }}"
  #     dnac_port: "{{ dnac_port }}"
  #     dnac_version: "{{ dnac_version }}"
  #     dnac_debug: "{{ dnac_debug }}"
  #     state: absent
  #     siteNameHierarchy: Global/San Francisco
  #   register: result

  # - name: Show result
  #   debug:
  #     msg: "{{ result }}"
  #   when:
  #     - result is defined
