---
- name: Sample playbook for SDA Host Port Onboarding Module
  hosts: dnac_servers
  gather_facts: false

  vars_files:
    - "credentials.yml"

  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: true
      dnac_log_level: INFO
      dnac_log_append: false
      config_verify: true

  tasks:
    - name: Onboard Hosts
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: merged
        config:
          - ip_address: "204.1.2.2"
            port_assignment_details:
              - interface_name: "FortyGigabitEthernet1/1/1"
                connected_device_type: "TRUNKING_DEVICE"

              - interface_name: "FortyGigabitEthernet1/1/2"
                connected_device_type: "TRUNKING_DEVICE"
                authentication_template_name: "No Authentication"
                interface_description: "Trunk Port"

              # Create Access Points
              - interface_name: "FortyGigabitEthernet2/1/1"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"

              - interface_name: "FortyGigabitEthernet2/1/2"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"
                authentication_template_name: "No Authentication"
                interface_description: "Access Point Port"

              - interface_name: "GigabitEthernet1/1/1"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"
                authentication_template_name: "Open Authentication"
                interface_description: "Access Point Port"

              - interface_name: "GigabitEthernet1/1/2"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"
                authentication_template_name: "Closed Authentication"
                interface_description: "Access Point Port"

              - interface_name: "GigabitEthernet1/1/3"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"
                authentication_template_name: "Low Impact"
                interface_description: "Access Point Port"

              # Create User Devices
              - interface_name: "GigabitEthernet1/1/4"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_VLAN_23"

              - interface_name: "GigabitEthernet2/1/1"
                connected_device_type: "USER_DEVICE"
                voice_vlan_name: "VOICE_VLAN_23"

              - interface_name: "GigabitEthernet2/1/2"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_23"
                voice_vlan_name: "VOICE_VLAN_23"

              - interface_name: "GigabitEthernet2/1/3"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_23"
                voice_vlan_name: "VOICE_VLAN_23"
                security_group_name: "Guests"

              - interface_name: "GigabitEthernet2/1/4"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_23"
                voice_vlan_name: "VOICE_VLAN_23"
                security_group_name: "Guests"
                authentication_template_name: "No Authentication"

              - interface_name: "GigabitEthernet2/1/4"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_23"
                security_group_name: "Guests"
                authentication_template_name: "Closed Authentication"

              - interface_name: "GigabitEthernet2/1/4"
                connected_device_type: "USER_DEVICE"
                voice_vlan_name: "VOICE_VLAN_23"
                authentication_template_name: "Low Impact"
                interface_description: "User Device"

            port_channel_details:
              # Default protocol is ON for TRUNK
              - interface_names: ["TenGigabitEthernet1/0/37", "TenGigabitEthernet1/0/38", "TenGigabitEthernet1/0/39"]
                connected_device_type: "TRUNK"

              - interface_names: ["TenGigabitEthernet1/0/43", "TenGigabitEthernet1/0/44"]
                connected_device_type: "TRUNK"
                protocol: "ON"

              - interface_names: ["TenGigabitEthernet1/0/45", "TenGigabitEthernet1/0/46", "TenGigabitEthernet1/0/47", "TenGigabitEthernet1/0/48"]
                connected_device_type: "TRUNK"
                protocol: "LACP"

              - interface_names: ["TenGigabitEthernet1/1/2", "TenGigabitEthernet1/1/3", "TenGigabitEthernet1/1/4"]
                connected_device_type: "TRUNK"
                protocol: "PAGP"
                port_channel_descrption: "Trunk port channel"

              # Default protocol for EXTENDED_NODE is PAGP
              - interface_names: ["TenGigabitEthernet1/1/5", "TenGigabitEthernet1/1/6"]
                connected_device_type: "EXTENDED_NODE"

              - interface_names: ["TenGigabitEthernet1/1/7", "TenGigabitEthernet1/1/8"]
                connected_device_type: "EXTENDED_NODE"
                protocol: "PAGP"
                port_channel_descrption: "extended node port channel"

    - name: Update Hosts
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: merged
        config:
          - hostname: "NY-EN-9300.cisco.local"
            port_assignment_details:
              # update
              - interface_name: "FortyGigabitEthernet1/1/1"
                connected_device_type: "TRUNKING_DEVICE"
                interface_description: "Trunk Port at interface 111"

              # no update
              - interface_name: "FortyGigabitEthernet2/1/1"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"
                authentication_template_name: "No Authentication"

              # update
              - interface_name: "FortyGigabitEthernet2/1/2"
                connected_device_type: "ACCESS_POINT"
                data_vlan_name: "AG_23"
                authentication_template_name: "No Authentication"
                interface_description: "Access Point Port at 212"

              # update - change data vlan
              - interface_name: "GigabitEthernet1/1/4"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_23"

              # updatem - change voice to data vlan
              - interface_name: "GigabitEthernet2/1/1"
                connected_device_type: "USER_DEVICE"
                data_vlan_name: "AG_VLAN_23"

              # update - remove data vlan
              - interface_name: "GigabitEthernet2/1/2"
                connected_device_type: "USER_DEVICE"
                voice_vlan_name: "VOICE_VLAN_23"

              # update - change authentication template
              - interface_name: "GigabitEthernet2/1/4"
                connected_device_type: "USER_DEVICE"
                voice_vlan_name: "VOICE_VLAN_23"
                authentication_template_name: "No Authentication"
                interface_description: "User Device"

            port_channel_details:
              # update - add description
              - interface_names: ["TenGigabitEthernet1/0/37", "TenGigabitEthernet1/0/38", "TenGigabitEthernet1/0/39"]
                connected_device_type: "TRUNK"
                port_channel_descrption: "Trunk port channel"

              # update - change device type from extended_node to trunk
              - interface_names: ["TenGigabitEthernet1/1/5", "TenGigabitEthernet1/1/6"]
                connected_device_type: "TRUNK"

              # update - change device type from trunk to extended node when protocol is pagp
              - interface_names: ["TenGigabitEthernet1/1/2", "TenGigabitEthernet1/1/3", "TenGigabitEthernet1/1/4"]
                connected_device_type: "EXTENDED_NODE"
                protocol: "PAGP"
                port_channel_descrption: "Trunk port channel"

              # no update - remove port_channel_description
              - interface_names: ["TenGigabitEthernet1/1/2", "TenGigabitEthernet1/1/3", "TenGigabitEthernet1/1/4"]
                connected_device_type: "TRUNK"
                protocol: "PAGP"

    - name: Delete specific host that meets the filterting criteria
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: deleted
        config:
          - hostname: "NY-EN-9300.cisco.local"

            port_assignment_details:
              - interface_name: "FortyGigabitEthernet2/1/1"
                data_vlan_name: "AG_23"

            port_channel_details:
              - port_channel_name: "Port-channel1"
                connected_device_type: "TRUNK"

    - name: Delete Multiple port assignments or port channels with interface_name and port_channel_name
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: deleted
        config:
          # Delete multiple port assignments or port channels with interface_name and port_channel_name
          - ip_address: "204.1.2.2"

            port_assignment_details:
              # Delete port assignments by interface name
              - interface_name: "FortyGigabitEthernet1/1/2"
              - interface_name: "FortyGigabitEthernet1/1/1"

            port_channel_details:
              # Delete port channels by port_channel_name
              - port_channel_name: "Port-channel2"
              - port_channel_name: "Port-channel3"

    - name: Delete port assignments and port channels using filter parameters
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: deleted
        config:
          # Delete all the interfaces and port channels that have specific parameter assigned
          - hostname: "NY-EN-9300.cisco.local"
            port_assignment_details:
              # all interfaces that have data_vlan_name - AG_23 assigned
              - data_vlan_name: "AG_23"

            port_channel_details:
              # all port channels that have TRUNK device type
              - connected_device_type: "TRUNK"

    - name: Delete port assignments and port channels using filter parameters
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: deleted
        config:
          - ip_address: "204.1.2.2"
            port_assignment_details:
              # all interfaces that have data_vlan_name - AG_VLAN_23 assigned
              - data_vlan_name: "AG_VLAN_23"

              # all interfaces that have voice_vlan_name - VOICE_VLAN_23 assigned
              - voice_vlan_name: "VOICE_VLAN_23"

            port_channel_details:
              # all port channels that have an extended_node device type
              - connected_device_type: "EXTENDED_NODE"

    - name: Delete ALL hosts on the device fabric by provided just the hostname OR IP address
      cisco.dnac.sda_host_port_onboarding_workflow_manager:
        <<: *dnac_login
        state: deleted
        config:
          - ip_address: "204.1.2.2"
