- hosts: localhost
  vars_files:
    - credentials.yml
  gather_facts: no
  connection: local
  tasks:
    - name: Create network functions
      cisco.dnac.network_settings_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_version: "{{dnac_version}}"
        dnac_log: True
        dnac_log_level: DEBUG
        dnac_log_append: True
        # dnac_log_file_path: "{{ dnac_log_file_path }}"
        state: merged
        config_verify: True
        config:
        - network_management_details:
          - site_name: Global
            settings:
              # network_aaa:
              #   server_type: ISE
              #   pan_address: 10.197.156.78
              #   primary_server_address: 100.1.1.55
              #   protocol: RADIUS
              dhcp_server:
              - 10.197.156.94
              timezone: GMT
              wireless_telemetry:
                enable_wireless_telemetry: True
              message_of_the_day:
                banner_message: hello
                retain_existing_banner: True
              