---
- name: Generate access point playbook configuration from Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    # Example 1: Generate all access point configurations
    - name: Generate complete access point configuration
      cisco.dnac.accesspoint_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/accesspoint_workflow_playbook.yml"
          file_mode: overwrite
          generate_all_configurations: true

    # Example 2: Generate access point provision configurations by sites
    - name: Generate access point provision configurations by sites
      cisco.dnac.accesspoint_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/accesspoint_workflow_playbook_site_base.yml"
          file_mode: "append"
          global_filters:
            site_list:
              - Global/USA/SAN JOSE/SJ_BLD23/FLOOR1
              - Global/USA/SAN JOSE/SJ_BLD23/FLOOR2
              - Global/USA/SAN JOSE/SJ_BLD23/FLOOR4

    # Example 3: Generate access point provision configurations by hostnames
    - name: Generate access point provision configurations by hostnames
      cisco.dnac.accesspoint_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/accesspoint_workflow_playbook_hostname_base.yml"
          file_mode: "append"
          global_filters:
            provision_hostname_list:
              - AP6849.9275.2910
              - Cisco_9120AXE_IP4-01

    # Example 4: Generate access point configurations by AP config hostnames
    - name: Generate access point configurations by AP config hostnames
      cisco.dnac.accesspoint_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/accesspoint_workflow_playbook_apconfig_base.yml"
          file_mode: overwrite
          global_filters:
            accesspoint_config_list:
              - AP6849.9275.2910
              - Cisco_9120AXE_IP4-01

    # Example 5: Generate access point provision configurations by AP hostnames
    - name: Generate access point provision configurations by AP hostnames
      cisco.dnac.accesspoint_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/accesspoint_workflow_playbook_host_provision_base.yml"
          file_mode: "overwrite"
          global_filters:
            accesspoint_provision_config_list:
              - AP687D.B402.1614-AP-Test6
              - Test_AP1

    # Example 6: Generate access point provision configurations by MAC addresses
    - name: Generate access point provision configurations by MAC addresses
      cisco.dnac.accesspoint_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/accesspoint_workflow_playbook_mac_address_base.yml"
          file_mode: "overwrite"
          global_filters:
            accesspoint_provision_config_mac_list:
              - a4:88:73:d0:53:60
              - 2c:e3:8e:af:d2:e0
