---
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Import certificate file
      cisco.dnac.authentication_import_certificate:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        certFilePath: ./files/test.template
        pkFilePath: ./files/test.template
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
