---
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Import image file
      cisco.dnac.swim_import_local:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        filePath: fullpath/playbooks/files/test.template # string
        isThirdParty: true # boolean
        thirdPartyApplicationType: SomeValue # string
        thirdPartyImageFamily: SomeValue # string
        thirdPartyVendor: SomeValue # string
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
