---
- name: Generate network switch profile playbook configuration from Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    # Example 1: Generate all switch profile configurations
    - name: Generate complete switch profile configuration
      cisco.dnac.network_profile_switching_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/network_profile_switching_workflow_playbook.yml"
          file_mode: "overwrite"
          generate_all_configurations: true

    # Example 2: Generate switch profile configurations using profile name global filters
    - name: Generate switch profile configurations by profile names
      cisco.dnac.network_profile_switching_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/network_profile_switching_workflow_playbook_profilebase.yml"
          file_mode: "overwrite"
          global_filters:
            profile_name_list:
              - Test Profile BF3
              - Campus_Access_Switch1

    # # Example 3: Generate switch profile configurations using template name global filters
    - name: Generate switch profile configurations by templates
      cisco.dnac.network_profile_switching_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/network_profile_switching_workflow_playbook_templatebase.yml"
          file_mode: "overwrite"
          global_filters:
            day_n_template_list:
              - evpn_l2vn_anycast_template

    # # Example 4: Generate switch profile configurations using site name global filters
    - name: Generate switch profile configurations by sites
      cisco.dnac.network_profile_switching_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          file_path: "tmp/network_profile_switching_workflow_playbook_sitebase.yml"
          global_filters:
            site_list:
              - Global/USA/SAN JOSE/SJ_BLD21/FLOOR1
              - Global/USA/SAN JOSE/SJ_BLD23/FLOOR2
