---
- name: Generates Fabric VLANs, Virtual Networks, and Anycast Gateways for SDA in Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    # Example 2: Generate all configurations with custom file path
    - name: Generate the playbook config for all Fabric VLANs, Virtual Networks, and Anycast Gateways in Cisco Catalyst Center
      cisco.dnac.sda_fabric_virtual_networks_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log_level: DEBUG
        dnac_log: true
        state: gathered
        file_path: "tmp/all_configurations.yml"
        file_mode: "overwrite"
