---
- name: SDA Host Port Onboarding Playbook Generator Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - credentials.yml
  tasks:
    - name: Generate YAML playbook for host port onboarding workflow manager
        which includes all fabric sites's host port onboarding details
      cisco.dnac.sda_host_port_onboarding_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        file_mode: "overwrite"

    - name: Generate YAML Configuration with File Path specified
      cisco.dnac.sda_host_port_onboarding_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        file_path: "host_onboarding_playbook.yml"
        file_mode: "overwrite"

    - name: Generate YAML Configuration with specific component port assignments filters
      cisco.dnac.sda_host_port_onboarding_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        file_path: "host_onboarding_playbook.yml"
        file_mode: "overwrite"
        config:
          component_specific_filters:
            components_list: ["port_assignments"]
            port_assignments:
              - fabric_site_name_hierarchy: "Global/California/23"
                device_ips:
                  - 10.195.120.219

    - name: Generate YAML Configuration with specific component port channels filters
      cisco.dnac.sda_host_port_onboarding_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        file_path: "host_onboarding_playbook.yml"
        file_mode: "overwrite"
        config:
          component_specific_filters:
            components_list: ["port_channels"]
            port_channels:
              - fabric_site_name_hierarchy: "Global/Site_India/Karnataka/Bangalore"
                device_ips:
                  - 10.195.120.219

    - name: Generate YAML Configuration with specific component wireless ssids filters
      cisco.dnac.sda_host_port_onboarding_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        file_path: "host_onboarding_playbook.yml"
        file_mode: "overwrite"
        config:
          component_specific_filters:
            components_list: ["wireless_ssids"]
            wireless_ssids:
              fabric_site_name_hierarchy:
                - "Global/Site_India/Karnataka/Bangalore"
