---
- name: Site intent
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Get site info and updating site details
      cisco.dnac.site_intent:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        state: merged
        config:
          - site:
              floor:
                name: Test_Floor2
                parent_name: 'Global/USA/San Francisco/BGL_18'
                length: "101"
                width: "75"
                height: "50"
                rf_model: 'Cubes And Walled Offices'
                floor_number: 3
          - site:
              area:
                name: Canada
                parent_name: 'Global'
            type: area
