---
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Create tag with name "MyNewTag"
      cisco.dnac.tag:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        state: present
        description: My Tag
        name: MyNewTag
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Get task status
      cisco.dnac.task_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        taskId: "{{ result.dnac_response.response.taskId }}"
      when:
        - result.dnac_response is defined
        - result.dnac_response.response is defined
        - result.dnac_response.response.taskId is defined
      register: task_result

    - name: Show status of create tag operation
      ansible.builtin.debug:
        msg: "{{ task_result.dnac_response.response }}"
      when:
        - task_result is defined
        - task_result.dnac_response is defined

    - name: Create the same tag
      cisco.dnac.tag:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        state: present
        description: My Tag 1
        name: MyNewTag
      register: result

    - name: Get task status
      cisco.dnac.task_tree_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        taskId: "{{ result.dnac_response.response.taskId }}"
      when:
        - result.dnac_response is defined
        - result.dnac_response.response is defined
        - result.dnac_response.response.taskId is defined
      register: task_tree_result

    - name: Show status of update tag operation
      ansible.builtin.debug:
        msg: "{{ task_tree_result.dnac_response.response }}"
      when:
        - task_tree_result is defined
        - task_tree_result.dnac_response is defined

    - name: Get tag with name "MyNewTag"
      cisco.dnac.tag_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        name: MyNewTag
      register: result

    - name: Show tags with name "MyNewTag"
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Delete tag
      cisco.dnac.tag:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        state: absent
        name: MyNewTag
      register: result

    - name: Show deleted tags with name "MyNewTag"
      ansible.builtin.debug:
        msg: "{{ result }}"

    # - name: Get task status
    #   cisco.dnac.task_info:
    #     dnac_host: "{{ dnac_host }}"
    #     dnac_username: "{{ dnac_username }}"
    #     dnac_password: "{{ dnac_password }}"
    #     dnac_verify: "{{ dnac_verify }}"
    #     taskId: "{{ result.dnac_response.response.taskId }}"
    #   when:
    #     - result.dnac_response is defined
    #     - result.dnac_response.response is defined
    #     - result.dnac_response.response.taskId is defined
    #   register: task_tree_result

    # - name: Show status of delete tag operation
    #   debug:
    #     msg: "{{ task_tree_result.dnac_response.response }}"
    #   when:
    #     - task_tree_result is defined
    #     - task_tree_result.dnac_response is defined

    - name: Get tag with name "MyNewTag"
      cisco.dnac.tag_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        name: MyNewTag
      register: result

    - name: Show tags with name "MyNewTag"
      ansible.builtin.debug:
        msg: "{{ result }}"
