---
name: ansible-lint
on:
  pull_request:
    branches: ["main_redhat", "stable", "release/v*"]
  workflow_dispatch:
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          args: "--exclude playbooks/  --exclude tests/"
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
