---
name: main

on:
  pull_request:
  # pull_request_review:
  #   types: [submitted]

jobs:
  trigger-circleci:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    steps:
      - run: echo -n "${GITHUB_REF}" | sed -r 's/^refs\///' | sed -r 's/merge/head/' > github_ref
      - name: Store ref for circleci trigger
        uses: actions/upload-artifact@v4
        with:
          name: github_ref-${{ github.run_id }}
          path: github_ref
